<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>name</key>
	<string>HTML (Play 2.0)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|match|case|map|implicit|Html|String|import|true|false|else)\b</string>
			<key>name</key>
			<string>keyword.control.play</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string></string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.play</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{)\s+(\w+)\s+(\=&gt;)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;-</string>
			<key>name</key>
			<string>keyword.control.play</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.colon.scala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z$_][a-zA-Z0-9$_]*)\s*(:)\s+([A-Za-z0-9][\w|_|?|\.]*)?,?</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![\w,@])@(\w+(?:\.\w+)*)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.play_scala</string>
	<key>uuid</key>
	<string>C8B2DE49-EF0F-40B1-AE2F-FDE50693396B</string>
</dict>
</plist>
